name: Blackboard Scraper Automation

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 */1 * * *'    # Runs every hour at the 30-minute mark
  workflow_dispatch:       # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Environment Variables
      run: |
        echo "BLACKBOARD_USER=${{ secrets.BLACKBOARD_USER }}" >> $GITHUB_ENV
        echo "BLACKBOARD_PASSWORD=${{ secrets.BLACKBOARD_PASSWORD }}" >> $GITHUB_ENV

    - name: Add Project Root to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run Scraper Script
      run: python src/main.py
